"""empty message

Revision ID: f1b6396b9995
Revises: bb283c058066
Create Date: 2024-12-03 04:31:28.979272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b6396b9995'
down_revision: Union[str, None] = 'bb283c058066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mediafile', ['file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mediafile', type_='unique')
    # ### end Alembic commands ###
